```{r}
# 1. 讀取lvr_prices_big5.csv檔案
price = read.csv('./riii/hw/lvr_prices_big5.csv')
```

```{r}
# 2. 可使用哪個函式觀看檔案的資料結構
str(price)
price = price[, -23] # 刪除後面才要建立的price_per_sqmeter
```

```{r}
# 3. 請篩選出
# (1) city_land_type為住宅用
# (2) total_price > 0
# (3) building_sqmeter > 0
# (4) finish_ymd 非空值
# 的房屋資料,並存入house變數中
# ctrl + shift + c 多行註解
house = price[price$city_land_type=='住' & price$total_price>0 & price$building_sqmeter>0 & nchar(price$finish_ymd)>0, ]
```

```{r}
# 4. 使用house資料，利用房屋價格(total_price)及房屋平方米數(building_sqmeter)兩欄位，
#    產生一新欄位為每平方米價格(price_per_sqmeter)，並將其四捨五入到整數位
price_per_sqmeter = round(house$total_price / house$building_sqmeter, 0)
house = cbind(house, price_per_sqmeter)
```

```{r}
# 5. 使用house資料，利用scale() 將每平方米價格(price_per_sqmeter)欄位資料標準化
#    ，並剔除掉outlier資料(z-score > 3)
# scale(house$price_per_sqmeter)
house = house[abs(scale(house$price_per_sqmeter)) < 3,]
```

```{r}
# 6. 利用房屋完工日期(finish_ymd)產生一新變數為屋齡(building_age)加入house資料中
# Hint(1) 取得當前日期的函數為 Sys.Date()
# Hint(2) 一年請以365天計算，四捨五入至整數位
# Hint(3) 將運算完的資料轉為整數型態(integer)
house$finish_ymd = as.Date(house$finish_ymd)
building_age = as.integer(round((Sys.Date() - house$finish_ymd)/365, 0))
house = cbind(house, building_age)
```

```{r}
# 7. 讀取final資料夾下的house_danger檔案，並將house資料集和house_danger資料集
#    以left outer join方式合併，存回house變數中
dangerhouse = read.csv('./riii/hw/house_danger.csv')
house = merge(x = house, y = dangerhouse, by.x = 'Unnamed..0',by.y='ID', all.x = T)

# 檢查遺失值
# sum(is.na(house
# 移除遺失值
# house = house[complete.cases(house),]
```

```{r}
# 8. 將house資料以8:2的比例分為訓練集和測試集，將訓練集資料存在trainset變數中，
#   將測試集資料存在testset變數中

# 選擇變數
variable.list = names(house) %in% c('area','building_age','building_sqmeter','building_type','price_per_sqmeter','danger')
house = house[,variable.list]

idx <- sample(1:2, size=nrow(house), replace=T, prob=c(0.8, 0.2))
trainset = house[idx==1,]
testset = house[idx==2,]
```

```{r}
# 9. 用rpart套件建立一預測房屋是否為危樓(danger)的決策樹模型
#    請利用行政區(area), 屋齡(building_age), 房屋總平方米數(building_sqmeter),房屋類型(building_type)及
#   每平方米價格(price_per_sqmeter)5個變數作為解釋變數放入模型當中建模，並將模型存在house.rp變數中
library('rpart')
# ?rpart.control
con = rpart.control(minsplit=20,cp=0.01)
house.rp = rpart(danger~.,data=trainset,control = con)
```

```{r}
# 10. 利用plot()和text()畫出house.rp模型的決策樹
# ?plot.rpart
par(mfrow=c(1,1))
plot(house.rp)
text(house.rp)
```

```{r}
# 11. 請問此決策數是否需要進行剪枝(prune)？如需剪枝請將修剪後的模型存回house.rp中
summary(house.rp)$cptable
```

```{r}
# 12. 將測試集資料(testset)放入模型中進行驗證，
#     請問此模型的accuracy, precision, recall等績效分別為何?
library('caret')
library('e1071')
predictions = predict(house.rp,testset,type='raw')

```
